# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: neo4j-liquibase
services:
  app:
    image: neo4j-liquibase
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_NEO4J_URI=bolt://neo4j-liquibase-neo4j:7687
    ports:
      - 127.0.0.1:8080:8080
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      neo4j:
        condition: service_healthy
  neo4j:
    extends:
      file: ./neo4j.yml
      service: neo4j
